/* generated using openapi-typescript-codegen -- do no edit */
/* istanbul ignore file */
/* tslint:disable */
/* eslint-disable */

export type { AboutUsDetailsResponse } from './models/AboutUsDetailsResponse';
export type { AcceptedFarmApplicationData } from './models/AcceptedFarmApplicationData';
export type { AcceptFarmApplicationResponse } from './models/AcceptFarmApplicationResponse';
export type { AcceptSeedlingRequest } from './models/AcceptSeedlingRequest';
export type { AddFarmCropResponse } from './models/AddFarmCropResponse';
export type { AdminListResponse } from './models/AdminListResponse';
export type { AdminUser } from './models/AdminUser';
export type { AnalyticsOverviewPieChartResponse } from './models/AnalyticsOverviewPieChartResponse';
export type { AnalyticsOverviewUserFeedbackResponse } from './models/AnalyticsOverviewUserFeedbackResponse';
export type { Answer } from './models/Answer';
export type { AnswersSchema } from './models/AnswersSchema';
export type { ApplicantData } from './models/ApplicantData';
export type { Approach } from './models/Approach';
export type { ApproachSection } from './models/ApproachSection';
export type { ArchiveCropResponse } from './models/ArchiveCropResponse';
export type { ArchivedCrop } from './models/ArchivedCrop';
export type { AuditLog } from './models/AuditLog';
export type { Blog } from './models/Blog';
export type { BlogDraft } from './models/BlogDraft';
export type { BlogImage } from './models/BlogImage';
export type { BlogTag } from './models/BlogTag';
export type { BlogViewResponse } from './models/BlogViewResponse';
export type { CancelInvitationResponse } from './models/CancelInvitationResponse';
export type { ChangeEmailRequest } from './models/ChangeEmailRequest';
export type { ChangeNumberRequest } from './models/ChangeNumberRequest';
export type { CheckExistingApplicationResponse } from './models/CheckExistingApplicationResponse';
export type { ClientDetailsResponse } from './models/ClientDetailsResponse';
export type { CMSImage } from './models/CMSImage';
export type { Comment } from './models/Comment';
export type { CommentsSchema } from './models/CommentsSchema';
export type { CommonOverviewResponse } from './models/CommonOverviewResponse';
export type { CommunityCropReportResponseItem } from './models/CommunityCropReportResponseItem';
export type { CommunityCropReportsResponse } from './models/CommunityCropReportsResponse';
export type { CommunityCropReportsResponseV2 } from './models/CommunityCropReportsResponseV2';
export type { CommunityFarm } from './models/CommunityFarm';
export type { CommunityFarmData } from './models/CommunityFarmData';
export type { CommunityFarmProblem } from './models/CommunityFarmProblem';
export type { CommunityFarmProblemListResponse } from './models/CommunityFarmProblemListResponse';
export type { CommunityFarmResponse } from './models/CommunityFarmResponse';
export type { CommunityFarmsResponse } from './models/CommunityFarmsResponse';
export type { ConfirmNumberRequest } from './models/ConfirmNumberRequest';
export type { ConfirmPasswordRequest } from './models/ConfirmPasswordRequest';
export type { CreateBlogImageResponse } from './models/CreateBlogImageResponse';
export type { CreateBlogTagsResponse } from './models/CreateBlogTagsResponse';
export type { CreateDraftEventResponse } from './models/CreateDraftEventResponse';
export type { CreateDraftResponse } from './models/CreateDraftResponse';
export type { CreateEventTagsRequest } from './models/CreateEventTagsRequest';
export type { CreateEventTagsResponse } from './models/CreateEventTagsResponse';
export type { CreateLearningCreditsResponse } from './models/CreateLearningCreditsResponse';
export type { CreateLearningTagsResponse } from './models/CreateLearningTagsResponse';
export type { CreateResourceResponse } from './models/CreateResourceResponse';
export type { CropData } from './models/CropData';
export type { CropDistribution } from './models/CropDistribution';
export type { CropGalleryItem } from './models/CropGalleryItem';
export type { CropImage } from './models/CropImage';
export type { CropItem } from './models/CropItem';
export type { CropReport } from './models/CropReport';
export type { CropReportData } from './models/CropReportData';
export type { CropReportResponse } from './models/CropReportResponse';
export type { CropReportViewResponse } from './models/CropReportViewResponse';
export type { CropStatisticsResponse } from './models/CropStatisticsResponse';
export type { DeleteDraftLearningMaterialResponse } from './models/DeleteDraftLearningMaterialResponse';
export type { DeleteSuccessMessage } from './models/DeleteSuccessMessage';
export type { DeleteVoteAnswerResponse } from './models/DeleteVoteAnswerResponse';
export type { DeleteVoteForumResponse } from './models/DeleteVoteForumResponse';
export type { DetailedResourceCount } from './models/DetailedResourceCount';
export type { DistrictFarmData } from './models/DistrictFarmData';
export type { DraftBlogListResponse } from './models/DraftBlogListResponse';
export type { ErrorResponse } from './models/ErrorResponse';
export type { Event } from './models/Event';
export type { EventDetails } from './models/EventDetails';
export type { EventDetailsResponse } from './models/EventDetailsResponse';
export type { EventPartnership } from './models/EventPartnership';
export type { EventSpeaker } from './models/EventSpeaker';
export type { EventSpeakerResponse } from './models/EventSpeakerResponse';
export type { EventTag } from './models/EventTag';
export type { ExistingFarmerApplication } from './models/ExistingFarmerApplication';
export type { FarmApplicationData } from './models/FarmApplicationData';
export type { FarmApplicationResponse } from './models/FarmApplicationResponse';
export type { FarmApplicationsResponse } from './models/FarmApplicationsResponse';
export type { FarmData } from './models/FarmData';
export type { FarmerAnswer } from './models/FarmerAnswer';
export type { FarmerApplication } from './models/FarmerApplication';
export type { FarmerGraphGrowthHarvestResponse } from './models/FarmerGraphGrowthHarvestResponse';
export type { FarmerGraphPiechartResponse } from './models/FarmerGraphPiechartResponse';
export type { FarmerGraphStackedBarData } from './models/FarmerGraphStackedBarData';
export type { FarmerGraphStackedBarResponse } from './models/FarmerGraphStackedBarResponse';
export type { FarmerGraphTotalHarvestResponse } from './models/FarmerGraphTotalHarvestResponse';
export type { FarmerInvitation } from './models/FarmerInvitation';
export type { FarmerInvitationResponse } from './models/FarmerInvitationResponse';
export type { FarmerTotalHarvestedData } from './models/FarmerTotalHarvestedData';
export type { FarmerTotalHarvestedResponse } from './models/FarmerTotalHarvestedResponse';
export type { FarmLandSizeAnalytics } from './models/FarmLandSizeAnalytics';
export type { FarmLandSizeByDistrict } from './models/FarmLandSizeByDistrict';
export type { FarmListResponse } from './models/FarmListResponse';
export type { FarmMember } from './models/FarmMember';
export type { FarmMemberApplication } from './models/FarmMemberApplication';
export type { FarmOverview } from './models/FarmOverview';
export type { FarmProblem } from './models/FarmProblem';
export type { FarmProblemListResponse } from './models/FarmProblemListResponse';
export type { FarmProblemPostResponse } from './models/FarmProblemPostResponse';
export type { FarmProblemResponse } from './models/FarmProblemResponse';
export type { FarmQuestion } from './models/FarmQuestion';
export type { FarmQuestionItem } from './models/FarmQuestionItem';
export type { FarmWithGrowthRate } from './models/FarmWithGrowthRate';
export type { FavouriteCropData } from './models/FavouriteCropData';
export type { ForumCount } from './models/ForumCount';
export type { ForumOverview } from './models/ForumOverview';
export type { GrowthRateDistribution } from './models/GrowthRateDistribution';
export type { GrowthRateResponse } from './models/GrowthRateResponse';
export type { HarvestDistribution } from './models/HarvestDistribution';
export type { HarvestedCropReportFormData } from './models/HarvestedCropReportFormData';
export type { HarvestedWitheredData } from './models/HarvestedWitheredData';
export type { ImageDetails } from './models/ImageDetails';
export type { InactiveFarmInfo } from './models/InactiveFarmInfo';
export type { InactiveFarmReport } from './models/InactiveFarmReport';
export type { InvitationItem } from './models/InvitationItem';
export type { LandingPageDetails } from './models/LandingPageDetails';
export type { LandingPageDetailsResponse } from './models/LandingPageDetailsResponse';
export type { LandingPageImage } from './models/LandingPageImage';
export type { LandingPageImageResponse } from './models/LandingPageImageResponse';
export type { LearningCredit } from './models/LearningCredit';
export type { LearningCredits } from './models/LearningCredits';
export type { LearningMaterial } from './models/LearningMaterial';
export type { LearningMaterialReport } from './models/LearningMaterialReport';
export type { LearningMaterialViewResponse } from './models/LearningMaterialViewResponse';
export type { LearningResource } from './models/LearningResource';
export type { LearningTag } from './models/LearningTag';
export type { ListApplicationsResponse } from './models/ListApplicationsResponse';
export type { ListDraftLearningMaterials } from './models/ListDraftLearningMaterials';
export type { ListDraftLearningMaterialsQuery } from './models/ListDraftLearningMaterialsQuery';
export type { ListDraftLearningMaterialsResponse } from './models/ListDraftLearningMaterialsResponse';
export type { ListFarmMembersResponse } from './models/ListFarmMembersResponse';
export type { ListInvitationsResponse } from './models/ListInvitationsResponse';
export type { ListMemberResponse } from './models/ListMemberResponse';
export type { ListPublishedLearningMaterials } from './models/ListPublishedLearningMaterials';
export type { ListPublishedLearningMaterialsResponse } from './models/ListPublishedLearningMaterialsResponse';
export type { ListRelatedLearningMaterialsResponse } from './models/ListRelatedLearningMaterialsResponse';
export type { ListToolRequestResponse } from './models/ListToolRequestResponse';
export type { ListUser } from './models/ListUser';
export type { ListUserResponse } from './models/ListUserResponse';
export type { MarkProblemAsResolvedRequest } from './models/MarkProblemAsResolvedRequest';
export type { Member } from './models/Member';
export type { Members } from './models/Members';
export type { MemberUpdate } from './models/MemberUpdate';
export type { MessageResponse } from './models/MessageResponse';
export type { MonthlyGrowthRate } from './models/MonthlyGrowthRate';
export type { NewAdminRequestBody } from './models/NewAdminRequestBody';
export type { NewAdminResponseData } from './models/NewAdminResponseData';
export type { NewAnswerResponse } from './models/NewAnswerResponse';
export type { NewCommentResponse } from './models/NewCommentResponse';
export type { NewCommunityCropReport } from './models/NewCommunityCropReport';
export type { NewCommunityFarmGallery } from './models/NewCommunityFarmGallery';
export type { NewCropReportRequest } from './models/NewCropReportRequest';
export type { NewCropReportResponse } from './models/NewCropReportResponse';
export type { NewCropRequest } from './models/NewCropRequest';
export type { NewCropResponse } from './models/NewCropResponse';
export type { NewDraftEvent } from './models/NewDraftEvent';
export type { NewEventPartnership } from './models/NewEventPartnership';
export type { NewEventPartnershipResponse } from './models/NewEventPartnershipResponse';
export type { NewEventSpeaker } from './models/NewEventSpeaker';
export type { NewEventSpeakerResponse } from './models/NewEventSpeakerResponse';
export type { NewFarmApplication } from './models/NewFarmApplication';
export type { NewFarmerInvitationRequest } from './models/NewFarmerInvitationRequest';
export type { NewFarmProblem } from './models/NewFarmProblem';
export type { NewFarmRequest } from './models/NewFarmRequest';
export type { NewFarmResponse } from './models/NewFarmResponse';
export type { NewHarvestTask } from './models/NewHarvestTask';
export type { NewLearningCredits } from './models/NewLearningCredits';
export type { NewLearningMaterial } from './models/NewLearningMaterial';
export type { NewLearningResource } from './models/NewLearningResource';
export type { NewLearningTags } from './models/NewLearningTags';
export type { NewPlantTask } from './models/NewPlantTask';
export type { NewQuestionSchema } from './models/NewQuestionSchema';
export type { NewReportedUser } from './models/NewReportedUser';
export type { NewSeedlingRequest } from './models/NewSeedlingRequest';
export type { NewSeedlingResponse } from './models/NewSeedlingResponse';
export type { NewTagRequestBody } from './models/NewTagRequestBody';
export type { NewTagResponse } from './models/NewTagResponse';
export type { NewToolRequest } from './models/NewToolRequest';
export type { NewUserFeedback } from './models/NewUserFeedback';
export type { Pagination } from './models/Pagination';
export type { PaginationData } from './models/PaginationData';
export type { Partner } from './models/Partner';
export type { PartnerUpdate } from './models/PartnerUpdate';
export type { PlantedCropReportFormData } from './models/PlantedCropReportFormData';
export type { PlantedCropsResponse } from './models/PlantedCropsResponse';
export type { PreDefinedMessages } from './models/PreDefinedMessages';
export type { PrivacyPolicyResponse } from './models/PrivacyPolicyResponse';
export type { ProblemMaterials } from './models/ProblemMaterials';
export type { PublishedBlog } from './models/PublishedBlog';
export type { PublishedBlogListResponse } from './models/PublishedBlogListResponse';
export type { PublishedBlogResponse } from './models/PublishedBlogResponse';
export type { PublishedLearningMaterial } from './models/PublishedLearningMaterial';
export type { PublishLearningMaterialResponse } from './models/PublishLearningMaterialResponse';
export type { QuestionSchema } from './models/QuestionSchema';
export type { QuestionsResponse } from './models/QuestionsResponse';
export type { QuestionTags } from './models/QuestionTags';
export type { QuestionViewSchema } from './models/QuestionViewSchema';
export type { ReadNotificationResponse } from './models/ReadNotificationResponse';
export type { RemoveLearningCreditsResponse } from './models/RemoveLearningCreditsResponse';
export type { RemoveLearningTagsResponse } from './models/RemoveLearningTagsResponse';
export type { RemoveResourceResponse } from './models/RemoveResourceResponse';
export type { ReportedQuestion } from './models/ReportedQuestion';
export type { ReportedQuestionList } from './models/ReportedQuestionList';
export type { ReportedUser } from './models/ReportedUser';
export type { ReportQuestionRequestBody } from './models/ReportQuestionRequestBody';
export type { ReportRequestBody } from './models/ReportRequestBody';
export type { ReportResponse } from './models/ReportResponse';
export type { RequestCount } from './models/RequestCount';
export type { ResetPasswordRequestBody } from './models/ResetPasswordRequestBody';
export type { ResourceCount } from './models/ResourceCount';
export type { SavedQuestionsResponse } from './models/SavedQuestionsResponse';
export type { SeedlingRequest } from './models/SeedlingRequest';
export type { SeedlingRequestListAllResponse } from './models/SeedlingRequestListAllResponse';
export type { SeedlingRequestListItem } from './models/SeedlingRequestListItem';
export type { SendOTPByNumber } from './models/SendOTPByNumber';
export type { SendResetTokenRequestBody } from './models/SendResetTokenRequestBody';
export type { ServerError } from './models/ServerError';
export type { SetFeaturedLearningMaterialResponse } from './models/SetFeaturedLearningMaterialResponse';
export type { Social } from './models/Social';
export type { SocialUpdate } from './models/SocialUpdate';
export type { SubfarmOverviewResponse } from './models/SubfarmOverviewResponse';
export type { Tag } from './models/Tag';
export type { TagList } from './models/TagList';
export type { TagSchema } from './models/TagSchema';
export type { TagsSchema } from './models/TagsSchema';
export type { TermsConditionsData } from './models/TermsConditionsData';
export type { TermsConditionsResponse } from './models/TermsConditionsResponse';
export type { Thumbnail } from './models/Thumbnail';
export type { ToolRequest } from './models/ToolRequest';
export type { UnpublishLearningMaterialResponse } from './models/UnpublishLearningMaterialResponse';
export type { UpdateAboutUsRequest } from './models/UpdateAboutUsRequest';
export type { UpdateAboutUsResponse } from './models/UpdateAboutUsResponse';
export type { UpdateAccessControl } from './models/UpdateAccessControl';
export { UpdateApplicationStatusRequest } from './models/UpdateApplicationStatusRequest';
export type { UpdateApproachRequest } from './models/UpdateApproachRequest';
export type { UpdateApproachResponse } from './models/UpdateApproachResponse';
export type { UpdateBlogRequest } from './models/UpdateBlogRequest';
export type { UpdateBlogResponse } from './models/UpdateBlogResponse';
export type { UpdateClientDetailsRequest } from './models/UpdateClientDetailsRequest';
export type { UpdateClientDetailsResponse } from './models/UpdateClientDetailsResponse';
export type { UpdateCommunityFarmRequest } from './models/UpdateCommunityFarmRequest';
export type { UpdateCommunityFarmResponse } from './models/UpdateCommunityFarmResponse';
export type { UpdateCropRequest } from './models/UpdateCropRequest';
export type { UpdateDraftEvent } from './models/UpdateDraftEvent';
export type { UpdateDraftEventResponse } from './models/UpdateDraftEventResponse';
export type { UpdateDraftResponse } from './models/UpdateDraftResponse';
export type { UpdateEventPartnershipResponse } from './models/UpdateEventPartnershipResponse';
export type { UpdateEventSpeaker } from './models/UpdateEventSpeaker';
export type { UpdateLandingRequest } from './models/UpdateLandingRequest';
export type { UpdateLandingResponse } from './models/UpdateLandingResponse';
export type { UpdateLearningMaterial } from './models/UpdateLearningMaterial';
export type { UpdatePasswordRequestBody } from './models/UpdatePasswordRequestBody';
export type { UpdatePrivacyPolicyRequest } from './models/UpdatePrivacyPolicyRequest';
export type { UpdatePrivacyPolicyResponse } from './models/UpdatePrivacyPolicyResponse';
export type { UpdateQuestionSchema } from './models/UpdateQuestionSchema';
export type { UpdateTermsConditionsRequest } from './models/UpdateTermsConditionsRequest';
export type { UpdateTermsConditionsResponse } from './models/UpdateTermsConditionsResponse';
export { UpdateToolRequestStatus } from './models/UpdateToolRequestStatus';
export type { UserAuthResponse } from './models/UserAuthResponse';
export type { UserCompletionSchema } from './models/UserCompletionSchema';
export type { UserFeedback } from './models/UserFeedback';
export type { UserFeedbackListResponse } from './models/UserFeedbackListResponse';
export type { UserFeedbackResponse } from './models/UserFeedbackResponse';
export type { UserLoginSchema } from './models/UserLoginSchema';
export type { UserNotificationResponse } from './models/UserNotificationResponse';
export type { UserObject } from './models/UserObject';
export type { UserProfile } from './models/UserProfile';
export type { UserRegisterSchema } from './models/UserRegisterSchema';
export type { UserSchema } from './models/UserSchema';
export type { UserUpdateProfile } from './models/UserUpdateProfile';
export type { VerifyOTP } from './models/VerifyOTP';
export type { VerifyOTPRequest } from './models/VerifyOTPRequest';
export type { VerifyOTPSuccessResponse } from './models/VerifyOTPSuccessResponse';
export type { ViewApplicationResponse } from './models/ViewApplicationResponse';
export type { ViewInvitationResponse } from './models/ViewInvitationResponse';
export type { VisionStatsResponse } from './models/VisionStatsResponse';
export { VoteAnswerSchema } from './models/VoteAnswerSchema';
export { VoteAnswerSuccessResponse } from './models/VoteAnswerSuccessResponse';
export type { VoteResponseSchema } from './models/VoteResponseSchema';
export type { ZodValidationError } from './models/ZodValidationError';

export { AccessService } from './services/AccessService';
export { AccountService } from './services/AccountService';
export { AuditLogsService } from './services/AuditLogsService';
export { AuthService } from './services/AuthService';
export { BlogsService } from './services/BlogsService';
export { CmsService } from './services/CmsService';
export { CommunityFarmService } from './services/CommunityFarmService';
export { CommunityFarmReportsService } from './services/CommunityFarmReportsService';
export { CommunityFarmTasksService } from './services/CommunityFarmTasksService';
export { CropService } from './services/CropService';
export { EventsService } from './services/EventsService';
export { FarmService } from './services/FarmService';
export { FarmProblemsService } from './services/FarmProblemsService';
export { FarmRequestService } from './services/FarmRequestService';
export { ForumsService } from './services/ForumsService';
export { LearningMaterialsService } from './services/LearningMaterialsService';
export { NotificationService } from './services/NotificationService';
export { ReportsService } from './services/ReportsService';
export { TagsService } from './services/TagsService';
export { UploaderService } from './services/UploaderService';
export { UserService } from './services/UserService';
